---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
taxonomies:
  category: "categories"
baseurl: "http://cool-story.github.io/brogrammer.today/"
title: "brogrammer.today"
canonifyurls: true
...
