---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://cool-story.github.io/brogrammer.today/"
title: "foobar test"
canonifyurls: true
...
